### ISSUE TITLE
Info only: Created package for Arch Linux

### ISSUE THREAD

**Issue by pezz** [WhiteRusssian/PySpy#1]
Hi there,

Just wanted to let you know that I've created a package for Arch Linux:

https://aur.archlinux.org/packages/pyspy/

I created a patch for a tiny tweak to config.py, but I'll leave it up to you if you'd like to incorporate it.

Cheers!

**Comment by WhiteRusssian** [comment]
Hi mate,

Thanks for making this available to everyone. Appreciate it. Out of curiosity, if you run the following command on Linux, what is the output?

Python
Import os
os.name

I might build the Linux paths into my config.py file permanently to make this easier in future.

**Comment by pezz** [comment]
Sounds great, and yeah os.name returns "posix" and platform.system() returns "Linux".

**Comment by WhiteRusssian** [comment]
Linux support added in v0.3.

Thanks for your help pezz.
