### ISSUE TITLE
Maintainence Offer

### ISSUE THREAD

**Issue by Crypta-Eve** [WhiteRusssian/PySpy#11]
Hey mate,

Saw your post regarding looking for a maintainer for PySpy.... Im happy to step up if you havent already found one. I am fairly strong with python and have become intimately familiar with mongodb through my other eve projects. While I have never used pythonanywhere, I imagine it is not difficult....

Im happy to keep this tool alive for you!

Kind Regards,

Crypta

**Comment by WhiteRusssian** [comment]
Thanks mate, just replied to you on Reddit.
