### ISSUE TITLE
Update window opens 404 page

### ISSUE THREAD

**Issue by Zulunia** [WhiteRusssian/PySpy#2]
**Describe the bug**
Upon opening it asks to update to 0.2 (coming from 0.1)
https://github.com/WhiteRusssian/PySpy/Download/

**To Reproduce**
Open and click update popup

**Expected behavior**

**Screenshots**

**System Environment:**
 - OS: Windows
 - OS 10
 - PySpy Version 0.1

**Additional context**

**Comment by WhiteRusssian** [comment]
Hi mate, thanks for reporting this.

This problem originates from v0.1 pointing to a bad URL for updates. This has already been fixed in v0.2.

Please go to https://github.com/WhiteRusssian/PySpy/releases/latest to download v0.2 manually.
