### ISSUE TITLE
PySpy crashes with Segfault on Arch Linux

### ISSUE THREAD

**Issue by Deliveranc3** [WhiteRusssian/PySpy#3]
**Describe the bug**
PySpy on Arch Linux does not open; crashes with segfault. Error text provided below.
```
(pyspy:5491): Gtk-WARNING **: 12:03:46.486: Negative content height -4 (allocation 20, extents 12x12) while allocating gadget (node scale, owner GtkScale)

(pyspy:5491): Gtk-WARNING **: 12:03:46.488: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node trough, owner GtkScale)
Segmentation fault (core dumped)
```

**To Reproduce**
Attempt to launch PySpy, via GUI or terminal.

**System Environment:**
 - OS: Arch Linux 
 - Kernel Version: 4.18.7-arch1-1-ARCH 
 - PySpy Version: 0.4-1
 - python Version: 3.7.0-3
 - python-pyperclip Version: 1.6.4-2
 - python-wxpython Version: 4.0.3-4

**Additional context**
Issue occurs both with the version of PySpy downloaded from AUR as well as directly from GitHub.

**Comment by WhiteRusssian** [comment]
Hi mate, since I do not have a Linux machine myself and only test on Mac OS X and Windows 10, I am not able to replicate this, however, a couple of posts suggest that it could have to do with the version of GTK you are using (e.g. https://www.eclipse.org/forums/index.php/t/1081230/). Which version of GTK are you using?

**Comment by Deliveranc3** [comment]
Thanks for checking into it. I currently have GTK 3.24.1-1 installed

**Comment by WhiteRusssian** [comment]
No problem, are you able to switch to GTK2 temporarily to test whether this solves the issue for you?

**Comment by Deliveranc3** [comment]
Unfortunately my system relies on GTK3 so I can't remove it outright. I do have GTK2 installed on my system still though. Is it possible to force wxpython to use GTK2 if that's the issue?

**Comment by WhiteRusssian** [comment]
I am not a Linux user but seems you could try to run this command `export SWT_GTK3=0` before launching pyspy. This would temporarily disable GTK3 for the current terminal session. Let me know if this works.

**Comment by Deliveranc3** [comment]
Ok so I just did a bunch of digging and debugging...looks like the GTK warnings aren't to blame after all. The segfault was apparently being caused by pyperclip because it was unable to read the clipboard. In order to read the clipboard on a Linux system, the xclip package must be installed. Once installed, PySpy functions normally, so this looks to be an issue with the Arch package dependencies so I'm going to submit that to the AUR maintainer.

**Comment by WhiteRusssian** [comment]
Glad you managed to fix it and thank you for sharing your findings with everyone here. Hope you enjoy PySpy.
