### ISSUE TITLE
[BUG] No alliances displayed

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [WhiteRusssian/PySpy#5]
**Describe the bug**
Alliance column is empty

**To Reproduce**
1. Ctrl+c on local
2. Check the pilot list, no alliances are displayed.

**Expected behavior**
The pilot's alliance should be displayed (It would be easy to guess pilots in the same fleet)

**System Environment:**
 - OS: Windows 10
 - OS Version: 1803
 - PySpy Version 0.4

**Comment by WhiteRusssian** [comment]
Could you please provide a list of pilot names where this is a problem. I am unable to reproduce this. I guess you are aware that not every pilot is necessarily part of an Alliance?

**Comment by Sakarias-Longhorn** [comment]
Not able to reproduce
