### ISSUE TITLE
[REQUEST] Localization

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [WhiteRusssian/PySpy#6]
It would be nice if we could choose the tool's localization, detected automatically from the OS default language.

Example : I'm french, my OS is in french, the application should switch automatically to French, but I could still go to a setting menu to change it back to english if I wanted to.

Note : I can provide French translation if needed.

**Comment by WhiteRusssian** [comment]
Appreciate your comment but to be honest I doubt will spend any time on localising PySpy.

**Comment by WhiteRusssian** [comment]
Appreciate your comment but to be honest I doubt will spend any time on localising PySpy.
